import { UserProfile, FieldInfo, DecisionTwin, WeatherData, SoilHealth, CropDiseaseResult, FieldObservationItem } from './types';

export const SEED_USER: UserProfile = {
  id: 'usr-thanjavur-01',
  name: 'Arun Kumar',
  tamilName: 'அருண் குமார்',
  phone: '+91 98421 55670',
  village: 'Vaduvur',
  district: 'Thanjavur',
  state: 'Tamil Nadu',
  language: 'ta',
};

export const SEED_FIELD: FieldInfo = {
  id: 'fld-vaduvur-north',
  name: 'North Field',
  tamilName: 'வடக்கு வயல்',
  crop: 'Paddy',
  cropTamil: 'நெல்',
  variety: 'BPT 5204 (Samba Mahsuri)',
  areaAcres: 2.4,
  plantingDate: '2026-07-15',
  cropAgeDays: 62,
  soilType: 'Clay Loam (வண்டல் களிமண்)',
  soilTypeTamil: 'வண்டல் களிமண்',
  irrigationSource: 'Canal & Submersible Borewell',
  location: 'Vaduvur Agraharam, Thanjavur',
};

export const SEED_DECISION: DecisionTwin = {
  id: 'dec-today-01',
  fieldId: 'fld-vaduvur-north',
  decisionType: 'WAIT',
  titleEn: 'Hold Irrigation',
  titleTa: 'இன்று தண்ணீர் விட வேண்டாம்',
  actionEn: 'Skip irrigation for the next 24-36 hours',
  actionTa: 'அடுத்த 24-36 மணி நேரத்திற்கு பாசனம் செய்யாமல் காத்திருக்கவும்',
  reasonEn: 'Current root-zone soil moisture is 68% (adequate) and 12-18mm rain is forecast within 36 hours. Irrigating now risks waterlogging.',
  reasonTa: 'மண்ணில் ஈரப்பதம் போதுமானதாக உள்ளது (68%). மேலும் அடுத்த 36 மணி நேரத்தில் 12-18 மி.மீ மழை வர வாய்ப்புள்ளது. எனவே இன்று தண்ணீர் விடாமல் காத்திருக்கலாம்.',
  confidence: 0.89,
  domain: 'IRRIGATION',
  evidence: {
    soilMoisturePct: 68,
    rainProbabilityPct: 74,
    rainfallNext24hMm: 14,
    satelliteCropState: 'Healthy Vegetation (NDVI 0.68)',
    recentAction: 'Canal irrigation applied 3 days ago',
  },
};

export const SEED_WEATHER: WeatherData = {
  location: 'Thanjavur, Tamil Nadu',
  temperatureC: 28,
  condition: 'Partly Cloudy',
  conditionTamil: 'ஓரளவு மேகமூட்டம்',
  summaryTa: '2 நாட்களுக்குள் மழை பெய்ய வாய்ப்புள்ளது',
  humidityPct: 60,
  windKmh: 12,
  rainfallMm: 0,
  rainProbabilityPct: 72,
  forecast: [
    { day: 'Today', dayTamil: 'இன்று', tempMax: 28, tempMin: 22, condition: 'Partly Cloudy', rainProb: 30 },
    { day: 'Tomorrow', dayTamil: 'நாளை', tempMax: 27, tempMin: 21, condition: 'Scattered Showers', rainProb: 75 },
    { day: 'Sat', dayTamil: 'சனி', tempMax: 26, tempMin: 21, condition: 'Moderate Rain', rainProb: 85 },
    { day: 'Sun', dayTamil: 'ஞாயிறு', tempMax: 28, tempMin: 22, condition: 'Light Rain', rainProb: 45 },
    { day: 'Mon', dayTamil: 'திங்கள்', tempMax: 29, tempMin: 23, condition: 'Clear Sun', rainProb: 15 },
  ],
};

export const SEED_SOIL: SoilHealth = {
  status: 'Good',
  statusTamil: 'நல்ல நிலை',
  suitabilityTextEn: 'Your soil is suitable for rice cultivation',
  suitabilityTextTa: 'உங்கள் மண் நெல் சாகுபடிக்கு மிகவும் உகந்தது',
  nutrients: {
    nitrogen: { level: 'Medium', value: '280 kg/ha', pct: 60 },
    phosphorus: { level: 'Low', value: '14 kg/ha', pct: 25 },
    potassium: { level: 'High', value: '320 kg/ha', pct: 85 },
    ph: { value: 6.8, label: '6.8 (Good)', pct: 70 },
    organicCarbon: { level: 'Medium', value: '0.62%', pct: 55 },
  },
  recommendationEn: 'Add organic manure or green manure (Daincha) to improve phosphorus availability and soil organic carbon.',
  recommendationTa: 'மண்ணின் பாஸ்பரஸ் அளவை உயர்த்த மக்கிய தொழு உரம் அல்லது தக்கைப்பூண்டு இடவும்.',
};

export const SEED_CROP_DISEASE: CropDiseaseResult = {
  crop: 'Rice / Paddy',
  cropTamil: 'நெல்',
  disease: 'Leaf Blight (in Rice)',
  diseaseTamil: 'இலை கருகல் நோய் (நெல்)',
  scientificName: 'Xanthomonas oryzae pv. oryzae',
  confidencePct: 87,
  severity: 'Moderate',
  imageUrl: 'https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=600&auto=format&fit=crop&q=80',
  symptomsEn: [
    'Elongated water-soaked lesions on leaf margins turning yellow-brown',
    'Wavy lesion margins progressing down the leaf blade',
    'Bacterial ooze droplets visible during humid morning hours',
  ],
  symptomsTa: [
    'இலை விளிம்புகளில் நீர் ஊறிய மஞ்சள்-பழுப்பு நிற புள்ளிகள்',
    'இலை நுனியிலிருந்து கீழ்நோக்கி படரும் கருகிய பகுதி',
    'அதிக ஈரப்பதமான காலை வேளையில் பாக்டீரியா திரவத் துளிகள்',
  ],
  actionItemsEn: [
    'Remove heavily affected leaves and burn them outside the field',
    'Use recommended bactericide/fungicide (Carbendazim 1g per litre or Streptocycline 1g/10L)',
    'Ensure proper water drainage and stop standing water for 48 hours',
    'Monitor for next 7 days and avoid excess urea/nitrogen fertilizer',
  ],
  actionItemsTa: [
    'அதிகமாக பாதிக்கப்பட்ட இலைகளை அகற்றி வயலுக்கு வெளியே அப்புறப்படுத்தவும்',
    'பரிந்துரைக்கப்பட்ட மருந்து: கார்பெண்டாசிம் (Carbendazim 1g/L) அல்லது ஸ்ட்ரெப்டோசைக்ளின் தெளிக்கவும்',
    'வயலில் தேங்கியுள்ள உபரி தண்ணீரை உடனடியாக வடிகட்டவும்',
    'அடுத்த 7 நாட்களுக்கு தொடர்ந்து கவனிக்கவும்; யூரியா உரமிடுவதை தற்காலிகமாக தவிர்க்கவும்',
  ],
  audioScriptTa: 'உங்கள் நெற்பயிரில் இலை கருகல் நோய் அறிகுறி எண்பத்தேழு சதவீதம் கண்டறியப்பட்டுள்ளது. பாதிக்கப்பட்ட இலைகளை அகற்றி, வயலில் நீர் தேங்காமல் பார்த்துக் கொள்ளவும். ஒரு லிட்டர் தண்ணீருக்கு ஒரு கிராம் கார்பெண்டாசிம் கலந்து தெளிக்க பரிந்துரைக்கப்படுகிறது.',
  audioScriptEn: 'Leaf blight detected with 87% confidence in your rice crop. Remove heavily infected leaves, ensure field drainage, and spray recommended fungicide at 1 gram per litre.',
};

export const SEED_HISTORY: FieldObservationItem[] = [
  {
    id: 'obs-01',
    date: '2026-09-15',
    relativeTime: 'Today',
    relativeTimeTa: 'இன்று',
    type: 'AI_ADVISORY',
    icon: '🧠',
    titleEn: 'VAYAL AI Recommendation',
    titleTa: 'VAYAL AI பரிந்துரை',
    detailEn: 'Irrigation not recommended — soil moisture 68% and rain expected',
    detailTa: 'பாசனம் பரிந்துரைக்கப்படவில்லை — ஈரப்பதம் 68% மற்றும் மழை வாய்ப்பு',
    source: 'VAYAL Decision Twin',
  },
  {
    id: 'obs-02',
    date: '2026-09-14',
    relativeTime: 'Yesterday',
    relativeTimeTa: 'நேற்று',
    type: 'RAIN',
    icon: '🌧️',
    titleEn: 'Rainfall Recorded',
    titleTa: 'மழை பதிவு',
    detailEn: '18 mm light to moderate rain received across Vaduvur sector',
    detailTa: 'வடுவூர் பகுதியில் 18 மி.மீ மிதமான மழை பெய்தது',
    source: 'Thanjavur Agro-Met Station',
  },
  {
    id: 'obs-03',
    date: '2026-09-14',
    relativeTime: 'Yesterday',
    relativeTimeTa: 'நேற்று',
    type: 'FARMER_OBSERVATION',
    icon: '👨🌾',
    titleEn: 'Farmer Observation (Voice)',
    titleTa: 'விவசாயி பதிவு (குரல்)',
    detailEn: '"Field soil is thoroughly wet and North channel is full"',
    detailTa: '"வயலில் நல்ல ஈரப்பதம் இருக்கு, வடக்கு வாய்க்காலில் தண்ணீர் நிறைஞ்சிருக்கு"',
    source: 'Arun Kumar (Voice Note)',
  },
  {
    id: 'obs-04',
    date: '2026-09-13',
    relativeTime: '2 days ago',
    relativeTimeTa: '2 நாட்களுக்கு முன்',
    type: 'IRRIGATION',
    icon: '💧',
    titleEn: 'Canal Irrigation',
    titleTa: 'வாய்க்கால் பாசனம்',
    detailEn: 'Completed 3 hours rotational flooding via Kallanai distributary',
    detailTa: 'கல்லணை வாய்க்கால் மூலம் 3 மணி நேர பாசனம் நிறைவுற்றது',
    source: 'Farmer Record',
  },
  {
    id: 'obs-05',
    date: '2026-09-12',
    relativeTime: '3 days ago',
    relativeTimeTa: '3 நாட்களுக்கு முன்',
    type: 'CROP_SCAN',
    icon: '📷',
    titleEn: 'Crop Doctor Inspection',
    titleTa: 'பயிர் மருத்துவர் பரிசோதனை',
    detailEn: 'Leaf Blight initial symptoms detected (87% confidence). Treatment logged.',
    detailTa: 'இலை கருகல் நோய் ஆரம்ப நிலை கண்டறியப்பட்டு சிகிச்சை குறிக்கப்பட்டது.',
    source: 'VAYAL Crop Vision',
  },
  {
    id: 'obs-06',
    date: '2026-09-02',
    relativeTime: '13 days ago',
    relativeTimeTa: '13 நாட்களுக்கு முன்',
    type: 'FERTILIZER',
    icon: '🧴',
    titleEn: 'Top Dressing Applied',
    titleTa: 'மேலுரம் இடுதல்',
    detailEn: 'Neem-coated Urea (25kg) + Potash (15kg) applied during tillering phase',
    detailTa: 'தூர்கட்டும் பருவத்தில் வேப்பம்பூசப்பட்ட யூரியா மற்றும் பொட்டாஷ் இடப்பட்டது',
    source: 'Farmer Record',
  },
];
